CREATE TABLE TRANSACTIONS(
    TRANSACT_ID INT PRIMARY KEY AUTO_INCREMENT,
    BLOCK_HASH VARCHAR(64),
    FROMADDRESS VARCHAR(64),
    TOADDRESS VARCHAR(64),
    AMOUNT FLOAT(10,2),
    TRANSACTION_HASH VARCHAR(64),
    STATUS ENUM('C','P','R')
);

CREATE TABLE BLOCK(
    TIMESTAMP INT,
    PREVIOUS_HASH VARCHAR(64),
    HASH VARCHAR(64),
    NONCE INT,
);
